name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, ]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels qlat-utils
        uses: pypa/cibuildwheel@v2.11.3
        with:
          package-dir: qlat-utils
          output-dir: wheelhouse

      - name: Build wheels qlat
        uses: pypa/cibuildwheel@v2.11.3
        with:
          package-dir: qlat
          output-dir: wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build SDist
      run: |
        cd qlat-utils ; pipx run build --sdist
        cd qlat ; pipx run build --sdist
        cd qlat-grid ; pipx run build --sdist

    - uses: actions/upload-artifact@v3
      with:
        path: qlat*/dist/*.tar.gz
