name: Ubuntu build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set PATH
      run: |
        echo "$HOME/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        export
        cat /proc/cpuinfo

    - name: Install Python packages
      run: |
        pip3 install --user psutil sympy numpy scipy meson

    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        type meson
        meson --version

    - name: Install Ubuntu packages
      run: |
        # sudo apt-get update
        sudo apt-get install -y libgsl-dev zlib1g-dev libssl-dev libopenmpi-dev libmpfr-dev ninja-build

    - name: Download dependencies
      run: |
        ./scripts/download-core.sh

    - name: Build dependencies
      run: |
        export num_proc=2
        ./scripts/setenv.default.sh
        ./scripts/fftw_mpi.sh
        ./scripts/fftwf_mpi.sh
        ./scripts/cuba.sh
        ./scripts/eigen.sh

    - name: Build Qlattice
      run: |
        export num_proc=2
        ./scripts/qlat.sh

    - name: Testing pylib qlat
      run: |
        ./scripts/qlat-examples-py.sh

    - name: Testing qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-cpp.sh

    - name: Copying logs
      run: |
        for i in examples-py/*.log examples-cpp/*/log ; do
          echo $i
          diff $HOME/qlat-build/default/qlat-examples/$i $i | grep 'CHECK: ' || echo Good
          cp $HOME/qlat-build/default/qlat-examples/$i $i
        done

    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '
