name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_qlat_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        qcore/bin/organize-env-path.py
        qcore/bin/show-env.py
    - name: Install Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y cython3 patchelf ninja-build python3-mpi4py python3-sympy python3-numpy python3-scipy python3-psutil libeigen3-dev libgsl-dev libopenmpi-dev libfftw3-dev zlib1g-dev libssl-dev libmpfr-dev
        sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra tex-gyre
    - name: Install Python packages
      run: |
        pip3 install --user meson
        pip3 install --user Sphinx myst-parser
    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        python3 -c 'import sys ; from mesonbuild import mesonmain; sys.exit(mesonmain.main())' --version
        type ninja
        ninja --version
    - name: Build dependencies
      run: |
        export num_proc=2
        ./scripts/setenv.default.sh
        ./scripts/qcore.sh
    - name: Build Qlattice
      run: |
        export num_proc=2
        ./scripts/qlat.sh
    - name: Build Qlattice documentation
      run: |
        export num_proc=2
        ./scripts/qlat-docs.sh
    - name: Testing pylib qlat
      run: |
        ./scripts/qlat-examples-py.sh
    - name: Testing qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-cpp.sh
    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '
    - uses: actions/upload-artifact@v3
      with:
        name: qlat-docs
        path: /home/runner/qlat-build/default/qlat-docs/share/doc
    - uses: actions/configure-pages@v3
    - uses: actions/upload-pages-artifact@v1
      with:
        path: /home/runner/qlat-build/default/qlat-docs/share/doc/qlat/html

  deploy_docs:
    # Add a dependency to the build job
    needs: build_qlat_ubuntu
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  build_pip_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        qcore/bin/organize-env-path.py
        qcore/bin/show-env.py
    - name: Install Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y cython3 patchelf ninja-build python3-mpi4py python3-sympy python3-numpy python3-scipy python3-psutil libeigen3-dev libgsl-dev libopenmpi-dev libfftw3-dev zlib1g-dev libssl-dev libmpfr-dev
    - name: Install Python packages
      run: |
        pip3 install --user meson
        pip3 install --user build meson-python wheel
    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        python3 -c 'import sys ; from mesonbuild import mesonmain; sys.exit(mesonmain.main())' --version
        type ninja
        ninja --version
    - name: Download dependencies
      run: |
        ./scripts/download-core.sh
    - name: Build dependencies
      run: |
        export num_proc=2
        ./scripts/setenv.default.sh
        ./scripts/qcore.sh
        ./scripts/c-lime.sh
        ./scripts/hdf5.sh
    - name: Build Grid-clehner
      run: |
        export num_proc=2
        ./scripts/grid-clehner.avx2.sh
    - name: Build GPT
      run: |
        export num_proc=2
        ./scripts/gpt.sh
    - name: Install Qlattice
      run: |
        export num_proc=2
        ./scripts/qlat-packages.sh
    - name: Testing pylib qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-py.sh
    - name: Testing qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-cpp.sh
    - name: Testing qlat grid
      run: |
        export num_proc=2
        ./scripts/qlat-examples-cpp-grid.sh
    - name: Testing pylib qlat gpt
      run: |
        export num_proc=2
        ./scripts/qlat-examples-py-gpt.sh
    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '
    - uses: actions/upload-artifact@v3
      with:
        name: qlat-packages
        path: /home/runner/qlat-build/default/qlat-packages/packages/*.tar.gz

  build_qlat_gpt_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        qcore/bin/organize-env-path.py
        qcore/bin/show-env.py
    - name: Install Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y cython3 patchelf ninja-build python3-mpi4py python3-sympy python3-numpy python3-scipy python3-psutil libeigen3-dev libgsl-dev libopenmpi-dev libfftw3-dev zlib1g-dev libssl-dev libmpfr-dev
        sudo apt-get install -y clang libomp-dev
    - name: Install Python packages
      run: |
        pip3 install --user meson
    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        python3 -c 'import sys ; from mesonbuild import mesonmain; sys.exit(mesonmain.main())' --version
        type ninja
        ninja --version
    - name: Download dependencies
      run: |
        ./scripts/download-core.sh
    - name: Build dependencies
      run: |
        export num_proc=2
        ./scripts/setenv.default.sh
        ./scripts/qcore.sh
        ./scripts/c-lime.sh
        ./scripts/hdf5.sh
    - name: Build Grid-clehner
      run: |
        export num_proc=2
        ./scripts/grid-clehner.avx2.sh
    - name: Build GPT
      run: |
        export num_proc=2
        ./scripts/gpt.sh
    - name: Build Qlattice
      run: |
        export num_proc=2
        ./scripts/qlat-grid.sh
    - name: Testing pylib qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-py.sh
    - name: Testing pylib qlat gpt
      run: |
        export num_proc=2
        ./scripts/qlat-examples-py-gpt.sh
    - name: Testing qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-cpp.sh
    - name: Testing qlat grid
      run: |
        export num_proc=2
        ./scripts/qlat-examples-cpp-grid.sh
    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '
    - name: Build more packages Grid
      run: |
        source ~/qlat-build/default/setenv.sh
        export num_proc=2
        export prefix=~/qlat-build/hadrons
        ./scripts/setenv.default.sh
        USE_COMPILER=clang ./scripts/grid.avx2.sh
    - name: Build more packages Hadrons
      run: |
        source ~/qlat-build/default/setenv.sh
        export num_proc=2
        export prefix=~/qlat-build/hadrons
        USE_COMPILER=clang ./scripts/hadrons.sh
    - name: Build more packages Grid-tblum
      run: |
        source ~/qlat-build/default/setenv.sh
        export num_proc=2
        export prefix=~/qlat-build/tblum
        ./scripts/setenv.default.sh
        USE_COMPILER=clang ./scripts/grid-tblum.avx2.sh
    - name: Build more packages Hadrons-tblum
      run: |
        source ~/qlat-build/default/setenv.sh
        export num_proc=2
        export prefix=~/qlat-build/tblum
        USE_COMPILER=clang ./scripts/hadrons-tblum.sh
    - name: Check error for Build more packages
      run: |
        [ -e $HOME/qlat-build/hadrons/Grid/lib/libGrid.a ]
        [ -e $HOME/qlat-build/hadrons/Grid/bin/grid-config ]
        [ -e $HOME/qlat-build/hadrons/Grid/bin/Mobius2p1fEOFA ]
        [ -e $HOME/qlat-build/hadrons/Grid/bin/Benchmark_dwf ]
        [ -e $HOME/qlat-build/hadrons/Grid/bin/Benchmark_dwf_fp32 ]
        [ -e $HOME/qlat-build/hadrons/Hadrons/lib/libHadrons.a ]
        [ -e $HOME/qlat-build/hadrons/Hadrons/bin/hadrons-config ]
        [ -e $HOME/qlat-build/hadrons/Hadrons/bin/HadronsXmlRun ]
        [ -e $HOME/qlat-build/hadrons/Hadrons/bin/HadronsContractor ]
        [ -e $HOME/qlat-build/tblum/Grid-tblum/lib/libGrid.a ]
        [ -e $HOME/qlat-build/tblum/Grid-tblum/bin/grid-config ]
        [ -e $HOME/qlat-build/tblum/Grid-tblum/bin/Mobius2p1fEOFA ]
        [ -e $HOME/qlat-build/tblum/Grid-tblum/bin/Benchmark_dwf ]
        [ -e $HOME/qlat-build/tblum/Grid-tblum/bin/Benchmark_dwf_fp32 ]
        [ -e $HOME/qlat-build/tblum/Hadrons-tblum/lib/libHadrons.a ]
        [ -e $HOME/qlat-build/tblum/Hadrons-tblum/bin/hadrons-config ]
        [ -e $HOME/qlat-build/tblum/Hadrons-tblum/bin/HadronsXmlRun ]
        [ -e $HOME/qlat-build/tblum/Hadrons-tblum/bin/HadronsContractor ]

  build_qlat_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        qcore/bin/organize-env-path.py
        qcore/bin/show-env.py
    - name: Install Brew packages
      run: |
        # brew update
        brew install ninja patchelf llvm open-mpi eigen fftw gsl zlib openssl@3 mpfr autoconf automake flock findutils pkg-config
        # brew upgrade
    - name: Install Python packages
      run: |
        pip3 install --user meson cython psutil sympy numpy scipy mpi4py
    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        python3 -c 'import sys ; from mesonbuild import mesonmain; sys.exit(mesonmain.main())' --version
        type ninja
        ninja --version
    - name: Build dependencies
      run: |
        export num_proc=3
        ./scripts/setenv.default.sh
        ./scripts/qcore.sh
    - name: Build Qlattice
      run: |
        export num_proc=3
        ./scripts/qlat.sh
    - name: Testing pylib qlat
      run: |
        ./scripts/qlat-examples-py.sh
    - name: Testing qlat
      run: |
        export num_proc=3
        ./scripts/qlat-examples-cpp.sh
    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '

  build_pip_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        qcore/bin/organize-env-path.py
        qcore/bin/show-env.py
    - name: Install Brew packages
      run: |
        # brew update
        brew install ninja patchelf llvm open-mpi eigen fftw gsl zlib openssl@3 mpfr autoconf automake flock findutils pkg-config
        # brew upgrade
    - name: Install Python packages
      run: |
        pip3 install --user meson cython psutil sympy numpy scipy mpi4py
        pip3 install --user build meson-python wheel
    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        python3 -c 'import sys ; from mesonbuild import mesonmain; sys.exit(mesonmain.main())' --version
        type ninja
        ninja --version
    - name: Download dependencies
      run: |
        ./scripts/download-core.sh
    - name: Build dependencies
      run: |
        export num_proc=3
        ./scripts/setenv.default.sh
        ./scripts/qcore.sh
        ./scripts/fftw.sh
        ./scripts/c-lime.sh
        ./scripts/hdf5.sh
    - name: Build Grid-clehner
      run: |
        export num_proc=3
        ./scripts/grid-clehner.gen16.sh
    - name: Build GPT
      run: |
        export num_proc=3
        ./scripts/gpt.sh
    - name: Install Qlattice
      run: |
        export num_proc=3
        ./scripts/qlat-packages.sh
    - name: Testing pylib qlat
      run: |
        export num_proc=3
        ./scripts/qlat-examples-py.sh
    - name: Testing qlat
      run: |
        export num_proc=3
        ./scripts/qlat-examples-cpp.sh
    - name: Testing qlat grid
      run: |
        export num_proc=3
        ./scripts/qlat-examples-cpp-grid.sh
    - name: Testing pylib qlat gpt
      run: |
        export num_proc=3
        ./scripts/qlat-examples-py-gpt.sh
    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '

  build_qlat_gpt_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        qcore/bin/organize-env-path.py
        qcore/bin/show-env.py
    - name: Install Brew packages
      run: |
        # brew update
        brew install ninja patchelf llvm open-mpi eigen fftw gsl zlib openssl@3 mpfr autoconf automake flock findutils pkg-config
        # brew upgrade
    - name: Install Python packages
      run: |
        pip3 install --user meson cython psutil sympy numpy scipy mpi4py
    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        python3 -c 'import sys ; from mesonbuild import mesonmain; sys.exit(mesonmain.main())' --version
        type ninja
        ninja --version
    - name: Download dependencies
      run: |
        ./scripts/download-core.sh
    - name: Build dependencies
      run: |
        export num_proc=3
        ./scripts/setenv.default.sh
        ./scripts/qcore.sh
        ./scripts/fftw.sh
        ./scripts/c-lime.sh
        ./scripts/hdf5.sh
    - name: Build Grid-clehner
      run: |
        export num_proc=3
        ./scripts/grid-clehner.gen16.sh
    - name: Build GPT
      run: |
        export num_proc=3
        ./scripts/gpt.sh
    - name: Build Qlattice
      run: |
        export num_proc=3
        ./scripts/qlat-grid.sh
    - name: Testing pylib qlat
      run: |
        export num_proc=3
        ./scripts/qlat-examples-py.sh
    - name: Testing pylib qlat gpt
      run: |
        export num_proc=3
        ./scripts/qlat-examples-py-gpt.sh
    - name: Testing qlat
      run: |
        export num_proc=3
        ./scripts/qlat-examples-cpp.sh
    - name: Testing qlat grid
      run: |
        export num_proc=3
        ./scripts/qlat-examples-cpp-grid.sh
    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '
    - name: Build more packages Grid
      run: |
        source ~/qlat-build/default/setenv.sh
        export num_proc=3
        export prefix=~/qlat-build/hadrons
        ./scripts/setenv.default.sh
        USE_COMPILER=clang ./scripts/grid.gen16.sh
    - name: Build more packages Hadrons
      run: |
        source ~/qlat-build/default/setenv.sh
        export num_proc=3
        export prefix=~/qlat-build/hadrons
        USE_COMPILER=clang ./scripts/hadrons.sh
    - name: Build more packages Grid-tblum
      run: |
        source ~/qlat-build/default/setenv.sh
        export num_proc=3
        export prefix=~/qlat-build/tblum
        ./scripts/setenv.default.sh
        USE_COMPILER=clang ./scripts/grid-tblum.gen16.sh
    - name: Build more packages Hadrons-tblum
      run: |
        source ~/qlat-build/default/setenv.sh
        export num_proc=3
        export prefix=~/qlat-build/tblum
        USE_COMPILER=clang ./scripts/hadrons-tblum.sh
    - name: Check error for Build more packages
      run: |
        [ -e $HOME/qlat-build/hadrons/Grid/lib/libGrid.a ]
        [ -e $HOME/qlat-build/hadrons/Grid/bin/grid-config ]
        [ -e $HOME/qlat-build/hadrons/Grid/bin/Mobius2p1fEOFA ]
        [ -e $HOME/qlat-build/hadrons/Grid/bin/Benchmark_dwf ]
        [ -e $HOME/qlat-build/hadrons/Grid/bin/Benchmark_dwf_fp32 ]
        [ -e $HOME/qlat-build/hadrons/Hadrons/lib/libHadrons.a ]
        [ -e $HOME/qlat-build/hadrons/Hadrons/bin/hadrons-config ]
        [ -e $HOME/qlat-build/hadrons/Hadrons/bin/HadronsXmlRun ]
        [ -e $HOME/qlat-build/hadrons/Hadrons/bin/HadronsContractor ]
        [ -e $HOME/qlat-build/tblum/Grid-tblum/lib/libGrid.a ]
        [ -e $HOME/qlat-build/tblum/Grid-tblum/bin/grid-config ]
        [ -e $HOME/qlat-build/tblum/Grid-tblum/bin/Mobius2p1fEOFA ]
        [ -e $HOME/qlat-build/tblum/Grid-tblum/bin/Benchmark_dwf ]
        [ -e $HOME/qlat-build/tblum/Grid-tblum/bin/Benchmark_dwf_fp32 ]
        [ -e $HOME/qlat-build/tblum/Hadrons-tblum/lib/libHadrons.a ]
        [ -e $HOME/qlat-build/tblum/Hadrons-tblum/bin/hadrons-config ]
        [ -e $HOME/qlat-build/tblum/Hadrons-tblum/bin/HadronsXmlRun ]
        [ -e $HOME/qlat-build/tblum/Hadrons-tblum/bin/HadronsContractor ]


#  build_wheels:
#    name: Build wheels on ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ ubuntu-latest, macos-latest, ]
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up QEMU
#        if: runner.os == 'Linux'
#        uses: docker/setup-qemu-action@v2
#        with:
#          platforms: all
#      - name: Build wheels qlat-utils
#        uses: pypa/cibuildwheel@v2.11.3
#        with:
#          package-dir: qlat-utils
#          output-dir: wheelhouse
#      - name: Build wheels qlat
#        uses: pypa/cibuildwheel@v2.11.3
#        with:
#          package-dir: qlat
#          output-dir: wheelhouse
#
#  make_sdist:
#    name: Make SDist
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Install Ubuntu packages
#      run: |
#        sudo apt-get update
#        sudo apt-get install -y libgsl-dev zlib1g-dev libssl-dev libeigen3-dev libopenmpi-dev libfftw3-mpi-dev libfftw3-dev libmpfr-dev
#    - name: Build sdist for qlat-utils
#      run: |
#        ( cd qlat-utils ; pipx run build --sdist )
#    - name: Build sdist for qlat
#      run: |
#        ( cd qlat ; pipx run build --sdist )
#    - name: Download dependencies
#      run: |
#        ./scripts/download-core.sh
#    - name: Build Grid-clehner
#      run: |
#        export num_proc=2
#        ./scripts/setenv.default.sh
#        ./scripts/qcore.sh
#        ./scripts/c-lime.sh
#        ./scripts/grid-clehner.avx2.sh
#    - name: Build sdist for qlat-grid
#      run: |
#        source ~/qlat-build/default/setenv.sh
#        ( cd qlat-grid ; pipx run build --sdist )
#    - name: Collecting sdist
#      run: |
#        mkdir -p dist
#        mv ./qlat*/dist/*.tar.gz ./dist
#    - uses: actions/upload-artifact@v3
#      with:
#        path: ./dist/*.tar.gz
