name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Show info
      run: |
        whoami
        pwd
        ls
        export

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libopenmpi-dev libfftw3-dev libgsl-dev

    - name: Download dependencies
      run: |
        ./scripts/download-core.sh || true

    - name: Build everything
      run: |
        export num_proc=4
        ./build.sh github || true

    - name: Testing qlat
      run: |
        make -C examples run || true
