name: Mac build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v3

    - name: Show info
      run: |
        whoami
        pwd
        ls
        export

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install Ubuntu packages
      run: |
        brew update
        brew install gsl zlib openssl@3 libomp open-mpi symengine numpy scipy mpfr meson ninja
        brew upgrade
        pip install psutil

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Download dependencies
      run: |
        ./scripts/download-core.sh || echo Failed

    - name: Build everything
      run: |
        export num_proc=4
        ./build.sh default || echo Failed

    - name: Testing qlat
      run: |
        ./scripts/qlat-examples-cpp.sh || echo Failed

    - name: Testing pylib qlat
      run: |
        ./scripts/qlat-examples-py.sh || echo Failed

    - name: Copying logs
      run: |
        for i in examples-py/*.log ; do
          cp $HOME/qlat-build/default/qlat-examples/$i $i
        done
        for i in examples-cpp/*/log ; do
          cp $HOME/qlat-build/default/qlat-examples/$i $i
        done

    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '
