name: Ubuntu pip build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set PATH
      run: |
        echo "$HOME/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        export
        cat /proc/cpuinfo

    - name: Install Python packages
      run: |
        pip3 install --user psutil sympy numpy scipy meson ninja meson-python wheel

    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        type meson
        meson --version
        type ninja
        ninja --version

    - name: Install Ubuntu packages
      run: |
        # sudo apt-get update
        sudo apt-get install -y libgsl-dev zlib1g-dev libssl-dev libeigen3-dev libopenmpi-dev libfftw3-mpi-dev libfftw3-dev libmpfr-dev libhdf5-mpi-dev libhdf5-dev patchelf

    - name: Install Qlattice
      run: |
        pip3 install -v --no-build-isolation ./qlat-utils
        pip3 install -v --no-build-isolation ./qlat

    - name: Setup testing environments
      run: |
        ./scripts/setenv.default.sh

    - name: Testing pylib qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-py.sh

    - name: Testing qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-cpp.sh

    - name: Download dependencies
      run: |
        ./scripts/download-core.sh

    - name: Build Grid
      run: |
        export num_proc=2
        ./scripts/c-lime.sh
        ./scripts/grid.avx2.sh

    - name: Build GPT
      run: |
        export num_proc=2
        ./scripts/gpt.sh

    - name: Install Qlat-Grid
      run: |
        source ~/qlat-build/default/setenv.sh
        pip3 install -v --no-build-isolation ./qlat-grid

    - name: Testing pylib qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-py-gpt.sh

    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '
