name: Mac pip build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set PATH
      run: |
        echo "$HOME/bin" >> $GITHUB_PATH
        echo "$HOME/Library/Python/3.11/bin" >> $GITHUB_PATH

    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        export
        sysctl -a

    - name: Install Python packages
      run: |
        pip3 install --user psutil sympy numpy scipy meson ninja meson-python wheel

    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        type meson
        meson --version
        type ninja
        ninja --version

    - name: Install Brew packages
      run: |
        # brew update
        brew install gsl zlib openssl@3 llvm open-mpi mpfr autoconf automake flock findutils eigen hdf5-mpi patchelf
        # brew upgrade

    - name: Build dependencies
      run: |
        export num_proc=3
        ./scripts/setenv.default.sh
        ./scripts/fftw_mpi.sh
        ./scripts/fftwf_mpi.sh

    - name: Install Qlattice
      run: |
        source ~/qlat-build/default/setenv.sh
        pip3 install -v --no-build-isolation ./qlat-utils
        pip3 install -v --no-build-isolation ./qlat

    - name: Testing pylib qlat
      run: |
        export num_proc=3
        ./scripts/qlat-examples-py.sh

    - name: Testing qlat
      run: |
        export num_proc=3
        ./scripts/qlat-examples-cpp.sh

    - name: Download dependencies
      run: |
        ./scripts/download-core.sh

    - name: Build Grid
      run: |
        export num_proc=3
        ./scripts/c-lime.sh
        ./scripts/grid.gen16.sh

    - name: Build GPT
      run: |
        export num_proc=3
        ./scripts/gpt.sh

    - name: Install Qlat-Grid
      run: |
        source ~/qlat-build/default/setenv.sh
        pip3 install -v --no-build-isolation ./qlat-grid

    - name: Testing pylib qlat
      run: |
        export num_proc=3
        ./scripts/qlat-examples-py-gpt.sh

    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '
