name: Ubuntu with GPT build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v3

    - name: Show info
      run: |
        whoami
        pwd
        ls
        export

    - name: Install Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libgsl-dev zlib1g-dev libssl-dev libopenmpi-dev python3-sympy python3-numpy python3-scipy python3-psutil libmpfr-dev meson ninja-build

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Download dependencies
      run: |
        ./scripts/download-core.sh || echo Failed

    - name: Build everything
      run: |
        export num_proc=4
        ./build.sh default-gpt || echo Failed

    - name: Testing qlat
      run: |
        ./scripts/qlat-examples-cpp.sh || echo Failed

    - name: Testing pylib qlat
      run: |
        ./scripts/qlat-examples-py-gpt.sh || echo Failed

    - name: Copying logs
      run: |
        for i in examples-py/log ; do
          cp $HOME/qlat-build/default/qlat-examples/$i $i
        done
        for i in examples-cpp/*/log ; do
          cp $HOME/qlat-build/default/qlat-examples/$i $i
        done

    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '
