name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_qlat_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        export
        cat /proc/cpuinfo
    - name: Install Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y cython3 patchelf ninja-build python3-sympy python3-numpy python3-scipy python3-psutil libeigen3-dev libgsl-dev libopenmpi-dev libfftw3-dev zlib1g-dev libssl-dev libmpfr-dev libhdf5-mpi-dev libhdf5-dev
    - name: Install Python packages
      run: |
        pip3 install --user meson
    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        type meson
        meson --version
        type ninja
        ninja --version
    - name: Build dependencies
      run: |
        export num_proc=2
        ./scripts/setenv.default.sh
    - name: Build Qlattice
      run: |
        export num_proc=2
        ./scripts/qlat.sh
    - name: Testing pylib qlat
      run: |
        ./scripts/qlat-examples-py.sh
    - name: Testing qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-cpp.sh
    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '

  build_pip_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        export
        cat /proc/cpuinfo
    - name: Install Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y cython3 patchelf ninja-build python3-sympy python3-numpy python3-scipy python3-psutil libeigen3-dev libgsl-dev libopenmpi-dev libfftw3-dev zlib1g-dev libssl-dev libmpfr-dev libhdf5-mpi-dev libhdf5-dev
    - name: Install Python packages
      run: |
        pip3 install --user meson
        pip3 install --user build meson-python wheel
    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        type meson
        meson --version
        type ninja
        ninja --version
    - name: Download dependencies
      run: |
        ./scripts/download-core.sh
    - name: Build dependencies
      run: |
        export num_proc=2
        ./scripts/setenv.default.sh
    - name: Install Qlattice
      run: |
        export num_proc=2
        ./scripts/qlat-packages.sh
    - name: Testing pylib qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-py.sh
    - name: Testing qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-cpp.sh
    - name: Build Grid
      run: |
        export num_proc=2
        ./scripts/c-lime.sh
        ./scripts/grid.avx2.sh
    - name: Install Qlat-Grid
      run: |
        export num_proc=2
        ./scripts/qlat-packages.sh
    - name: Build GPT
      run: |
        export num_proc=2
        ./scripts/gpt.sh
    - name: Testing pylib qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-py-gpt.sh
    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '
    - uses: actions/upload-artifact@v3
      with:
        path: /home/runner/qlat-build/default/qlat-packages/*.tar.gz

  build_qlat_gpt_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show info
      run: |
        whoami
        pwd
        export
        cat /proc/cpuinfo
    - name: Install Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y cython3 patchelf ninja-build python3-sympy python3-numpy python3-scipy python3-psutil libeigen3-dev libgsl-dev libopenmpi-dev libfftw3-dev zlib1g-dev libssl-dev libmpfr-dev libhdf5-mpi-dev libhdf5-dev
        sudo apt-get install -y clang libomp-dev
    - name: Install Python packages
      run: |
        pip3 install --user meson
    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        type meson
        meson --version
        type ninja
        ninja --version
    - name: Download dependencies
      run: |
        ./scripts/download-core.sh
    - name: Build dependencies
      run: |
        export num_proc=2
        ./scripts/setenv.default.sh
        ./scripts/eigen.sh
    - name: Build Grid
      run: |
        export num_proc=2
        ./scripts/c-lime.sh
        ./scripts/grid.avx2.sh
    - name: Build GPT
      run: |
        export num_proc=2
        ./scripts/gpt.sh
    - name: Build Qlattice
      run: |
        export num_proc=2
        ./scripts/qlat-grid.sh
    - name: Testing pylib qlat
      run: |
        ./scripts/qlat-examples-py-gpt.sh
        ./scripts/qlat-examples-py.sh
    - name: Testing qlat
      run: |
        export num_proc=2
        ./scripts/qlat-examples-cpp.sh
    - name: Build more packages Grid-tblum
      run: |
        export num_proc=2
        USE_COMPILER=clang ./scripts/grid-tblum.avx2.sh
    - name: Build more packages Hadrons-tblum
      run: |
        export num_proc=2
        USE_COMPILER=clang ./scripts/hadrons-tblum.sh
    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '
        [ -e $HOME/qlat-build/default/grid-tblum/lib/libGrid.a ]
        [ -e $HOME/qlat-build/default/grid-tblum/bin/grid-config ]
        [ -e $HOME/qlat-build/default/grid-tblum/bin/Mobius2p1fEOFA ]
        [ -e $HOME/qlat-build/default/grid-tblum/bin/Benchmark_dwf ]
        [ -e $HOME/qlat-build/default/grid-tblum/bin/Benchmark_dwf_fp32 ]

  build_qlat_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        export
        sysctl -a
    - name: Install Brew packages
      run: |
        # brew update
        brew install ninja patchelf llvm open-mpi eigen fftw gsl zlib openssl@3 mpfr autoconf automake flock findutils hdf5-mpi
        # brew upgrade
    - name: Install Python packages
      run: |
        pip3 install --user meson cython psutil sympy numpy scipy
    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        type meson
        meson --version
        type ninja
        ninja --version
    - name: Build dependencies
      run: |
        export num_proc=3
        ./scripts/setenv.default.sh
    - name: Build Qlattice
      run: |
        export num_proc=3
        ./scripts/qlat.sh
    - name: Testing pylib qlat
      run: |
        ./scripts/qlat-examples-py.sh
    - name: Testing qlat
      run: |
        export num_proc=3
        ./scripts/qlat-examples-cpp.sh
    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '

  build_pip_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        export
        sysctl -a
    - name: Install Brew packages
      run: |
        # brew update
        brew install ninja patchelf llvm open-mpi eigen gsl zlib openssl@3 mpfr autoconf automake flock findutils hdf5-mpi
        # brew upgrade
    - name: Install Python packages
      run: |
        pip3 install --user meson cython psutil sympy numpy scipy
        pip3 install --user build meson-python wheel
    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        type meson
        meson --version
        type ninja
        ninja --version
    - name: Download dependencies
      run: |
        ./scripts/download-core.sh
    - name: Build dependencies
      run: |
        export num_proc=3
        ./scripts/setenv.default.sh
        ./scripts/fftw.sh
        ./scripts/fftwf.sh
    - name: Install Qlattice
      run: |
        export num_proc=3
        ./scripts/qlat-packages.sh
    - name: Testing pylib qlat
      run: |
        export num_proc=3
        ./scripts/qlat-examples-py.sh
    - name: Testing qlat
      run: |
        export num_proc=3
        ./scripts/qlat-examples-cpp.sh
    - name: Build Grid
      run: |
        export num_proc=3
        ./scripts/c-lime.sh
        ./scripts/grid.gen16.sh
    - name: Install Qlat-Grid
      run: |
        export num_proc=3
        ./scripts/qlat-packages.sh
    - name: Build GPT
      run: |
        export num_proc=3
        ./scripts/gpt.sh
    - name: Testing pylib qlat
      run: |
        export num_proc=3
        ./scripts/qlat-examples-py-gpt.sh
    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '

  build_qlat_gpt_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        export
        sysctl -a
    - name: Install Brew packages
      run: |
        # brew update
        brew install ninja patchelf llvm open-mpi eigen gsl zlib openssl@3 mpfr autoconf automake flock findutils hdf5-mpi
        # brew upgrade
    - name: Install Python packages
      run: |
        pip3 install --user meson cython psutil sympy numpy scipy
    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        type meson
        meson --version
        type ninja
        ninja --version
    - name: Download dependencies
      run: |
        ./scripts/download-core.sh
    - name: Build dependencies
      run: |
        export num_proc=3
        ./scripts/setenv.default.sh
        ./scripts/eigen.sh
        ./scripts/fftw.sh
        ./scripts/fftwf.sh
    - name: Build Grid
      run: |
        export num_proc=3
        ./scripts/c-lime.sh
        ./scripts/grid.gen16.sh
    - name: Build GPT
      run: |
        export num_proc=3
        ./scripts/gpt.sh
    - name: Build Qlattice
      run: |
        export num_proc=3
        ./scripts/qlat-grid.sh
    - name: Testing pylib qlat
      run: |
        ./scripts/qlat-examples-py-gpt.sh
        ./scripts/qlat-examples-py.sh
    - name: Testing qlat
      run: |
        export num_proc=3
        ./scripts/qlat-examples-cpp.sh
    - name: Build more packages Grid-tblum
      run: |
        export num_proc=3
        ./scripts/grid-tblum.gen16.sh
    - name: Build more packages Hadrons-tblum
      run: |
        export num_proc=3
        ./scripts/hadrons-tblum.sh
    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '
        [ -e $HOME/qlat-build/default/grid-tblum/lib/libGrid.a ]
        [ -e $HOME/qlat-build/default/grid-tblum/bin/grid-config ]
        [ -e $HOME/qlat-build/default/grid-tblum/bin/Mobius2p1fEOFA ]
        [ -e $HOME/qlat-build/default/grid-tblum/bin/Benchmark_dwf ]
        [ -e $HOME/qlat-build/default/grid-tblum/bin/Benchmark_dwf_fp32 ]

#  build_wheels:
#    name: Build wheels on ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ ubuntu-latest, macos-latest, ]
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up QEMU
#        if: runner.os == 'Linux'
#        uses: docker/setup-qemu-action@v2
#        with:
#          platforms: all
#      - name: Build wheels qlat-utils
#        uses: pypa/cibuildwheel@v2.11.3
#        with:
#          package-dir: qlat-utils
#          output-dir: wheelhouse
#      - name: Build wheels qlat
#        uses: pypa/cibuildwheel@v2.11.3
#        with:
#          package-dir: qlat
#          output-dir: wheelhouse
#
#  make_sdist:
#    name: Make SDist
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Install Ubuntu packages
#      run: |
#        sudo apt-get update
#        sudo apt-get install -y libgsl-dev zlib1g-dev libssl-dev libeigen3-dev libopenmpi-dev libfftw3-mpi-dev libfftw3-dev libmpfr-dev libhdf5-mpi-dev libhdf5-dev patchelf
#    - name: Build sdist for qlat-utils
#      run: |
#        ( cd qlat-utils ; pipx run build --sdist )
#    - name: Build sdist for qlat
#      run: |
#        ( cd qlat ; pipx run build --sdist )
#    - name: Download dependencies
#      run: |
#        ./scripts/download-core.sh
#    - name: Build Grid
#      run: |
#        export num_proc=2
#        ./scripts/setenv.default.sh
#        ./scripts/c-lime.sh
#        ./scripts/grid.avx2.sh
#    - name: Build sdist for qlat-grid
#      run: |
#        source ~/qlat-build/default/setenv.sh
#        ( cd qlat-grid ; pipx run build --sdist )
#    - name: Collecting sdist
#      run: |
#        mkdir -p dist
#        mv ./qlat*/dist/*.tar.gz ./dist
#    - uses: actions/upload-artifact@v3
#      with:
#        path: ./dist/*.tar.gz
