name: Mac build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set PATH
      run: |
        echo "$HOME/bin" >> $GITHUB_PATH
        echo "$HOME/Library/Python/3.11/bin" >> $GITHUB_PATH

    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
        export
        sysctl -a

    - name: Install Python packages
      run: |
        pip3 install --user psutil sympy numpy scipy meson

    - name: Display Python version
      run: |
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
        python3 -c "import numpy as np ; np.show_config()"
        type meson
        meson --version

    - name: Install Brew packages
      run: |
        # brew update
        brew install gsl zlib openssl@3 llvm open-mpi mpfr ninja autoconf automake flock findutils
        # brew upgrade

    - name: Download dependencies
      run: |
        ./scripts/download-core.sh

    - name: Build dependencies
      run: |
        export num_proc=4
        ./scripts/setenv.default.sh
        ./scripts/fftw_mpi.sh
        ./scripts/fftwf_mpi.sh
        ./scripts/cuba.sh
        ./scripts/eigen.sh

    - name: Build Qlattice
      run: |
        export num_proc=4
        ./scripts/qlat.sh

    - name: Testing pylib qlat
      run: |
        ./scripts/qlat-examples-py.sh || echo Failed

    - name: Testing qlat
      run: |
        export num_proc=4
        ./scripts/qlat-examples-cpp.sh || echo Failed

    - name: Copying logs
      run: |
        for i in examples-py/*.log examples-cpp/*/log ; do
          echo $i
          diff $HOME/qlat-build/default/qlat-examples/$i $i | grep 'CHECK: ' || echo Good
          cp $HOME/qlat-build/default/qlat-examples/$i $i || echo Failed
        done

    - name: Check error
      run: |
        ! git diff | grep '^[+-]CHECK: '
